all:
	make -f 7G_ctrl.mak clean hex
	make -f 7G_dngl.mak clean hex

clean:
	make -f 7G_ctrl.mak clean
	make -f 7G_dngl.mak clean
	
flash:
	make -f 7G_ctrl.mak clean flash
	make -f 7G_dngl.mak clean flash